### PR TITLE
Add JSON/GraphQL parser (prettier 1.5)

### PR DESCRIPTION
**Pull request by vutran**
This PR adds the `json` option as an option for the parser configuration (originally from #16 but extracted as a separate PR as a release with the `json` parser hasn't landed on `npm` yet.

TODO:
- [x] bump `prettier` version on `package.json`
- [x] test locally: command, autoformat, etc.

### CODE REVIEW

**Comment by mitermayer** [comment]
prettier 1.5 has been release, we should be able to amend this PR!

**Comment by mitermayer** [comment]
Hi @vutran  please let me know if there is anything i can do here to help on the remainder checks

**Comment by vutran** [comment]
@mitermayer I'll be looking at this tonight.

**Comment by vutran** [comment]
@mitermayer Should be good to go. I've added the option for the new GraphQL parser as well.

**Comment by mitermayer** [comment]
Awesome! merging this now, will do a new release either tonight or tomorrow! Thanks a lot for your contribution!

**Pull request merged**
