### PR TITLE
Fix default settings

### PR DESCRIPTION
**Pull request by vutran**
This PR aligns the default settings for `prettier` based on the [current settings](https://github.com/prettier/prettier#options) specified in the `prettier` repo.

### CODE REVIEW

**Comment by mitermayer** [comment]
Hi @vutran , thank for submiting a pull request!

vim-prettier default settings differ from prettier intentionally. The default settings used on vim-prettier are meant to follow the same defaults that we use internally at Facebook and on Facebook open source projects. 

You can always overwrite the internal defaults by using our configuration hooks on your .vimrc.

Saying that based on your file changes I can seespliting this splitting into 2 potential PR's for this:

1. Updating our `README.md` and `doc/prettier.txt` to explain the reasoning behind our default settings choice.
2. Add support for JSON parsing

#### Updating our `README.md` and `doc/prettier.txt` to explain the reasoning behind our default settings choice

We could make it more clear the original intention of the vim-prettier default settings. Please feel free to submit a PR for it or update this PR to it.

#### Add support for JSON parsing

I have also noticed that you mentioned the support for JSON on the README, that is awesome. But can we do that on a different PR ? To add support for JSON we would also need to do some other updates:

1. copy `ftplugin/typescript.vim` to `ftplugin/json.vim` 
2. edit the newly created `ftplugin/json.vim`  and change the `parser` from `typescript` to `json`
3. update README.md:
     * update line `" flow|babylon|typescript|postcss|` to include `json` similar to what you did on this PR
     * update line `	\ 'for': ['javascript', 'typescript', 'css', 'less', 'scss'] }` to include `json`
     * update lines `autocmd BufWritePre...` to include`.json`
4. same updates done on README.md needs to be done on`doc/prettier.txt`
5. update package.json prettier version to the latest prettier that has support for the json parser throught the CLI
6. Test to make sure all is working :)

Thank you very much for contributing!

**Comment by mitermayer** [comment]
Also the json parser CLI setting is not yet been released to NPM, however we can have the PR ready for it. 

I believe there will be a new prettier release soon that will include it.

**Comment by vutran** [comment]
Sounds good. I'll update this PR with the changes mentioned and another one with the JSON settings.

**Comment by mitermayer** [comment]
Awesome!

**Pull request merged**
